[package]
name = "sped-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sped = { version = "0.1.0", path = "../sped-lib" }
image= { version = "0.25.1",features = ["rayon"] }
log = "0.4.21"
log4rs = "1.3.0"
imageproc = "0.25.0"